name: assessment
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  get_storage: ^2.1.1
  syncfusion_flutter_gauges: ^26.2.7
  flutter_slidable: ^3.0.1
  local_auth: ^2.1.8
  mocktail: ^1.0.4
  http: ^1.2.2

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Dubai-Bold.ttf
        - asset: assets/fonts/Dubai-Light.ttf
        - asset: assets/fonts/Dubai-Medium.ttf
        - asset: assets/fonts/Dubai-Regular.ttf
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Medium.ttf
        - asset: assets/fonts/Raleway-Thin.ttf
